---
kind: pipeline
# type: docker
name: default

clone:
  depth: 10

steps:
- name: test
  image: golang
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: "https://goproxy.io"
  commands:
  - go test

- name: build
  image: plugins/docker
  settings:
    registry: registry.shitangdama.cn
    repo: registry.shitangdama.cn/test/laki
    auto_tag: true
    dockerfile: Dockerfile
    username: shitangdama
    password:
      from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

# depends_on:
# - test

trigger:
  branch:
  - master
  event:
  - push