---
kind: pipeline
type: docker
name: default

# clone:
#   depth: 10

steps:
- name: code-test
  image: golang
  environment:
    GO111MODULE: on
    GOPROXY: "https://goproxy.io"
  commands:
  - go test
  when:
    branch:
      include:
        - feature/*
        - master
        - dev
    event:
      include:
        - push
        - pull_request

- name: build-docker
  image: plugins/docker
  settings:
    registry: registry.shitangdama.cn
    repo: registry.shitangdama.cn/dama/laki
    dockerfile: Dockerfile
    username: shitangdama
    password:
      from_secret: docker_password
    # tag:
    #   - ${DRONE_BRANCH##feature/}
  when:
    branch:
      - master

- name: semantic-release
  image: gtramontina/semantic-release:15.13.3
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  entrypoint:
    - semantic-release
  when:
    branch: master
    event: push

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host:
      - 118.24.142.70
    username: ubuntu
    password:
      from_secret: ssh_password
    port: 22
    script:
    - cd /home/ubuntu/dama/laki
    - docker-compose down
    - docker-compose up -d

# trigger:
#   branch:
#   - master
#   event:
#   - push