---
kind: pipeline
type: docker
name: default

# clone:
#   depth: 10

steps:
# - name: code-test
#   image: golang
#   environment:
#     GO111MODULE: on
#     GOPROXY: "https://goproxy.io"
#   commands:
#   - go test

# - name: test-docker
#   pull: if-not-exists
#   image: plugins/docker
#   settings:
#     registry: registry.shitangdama.cn
#     repo: registry.shitangdama.cn/dama/laki
#     auto_tag: true
#     dockerfile: Dockerfile
#     username: shitangdama
#     password:
#       from_secret: docker_password
#     when:
#       branch:
#         - master
#         - dev
#       event:
#         - push

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        - 118.24.142.70
      username: ubuntu
      password:
        from_secret: ssh_password
      port: 22
      script:
      - cd /home/ubuntu/dama/laki
      - docker-compose down
      - docker-compose up -d

trigger:
  branch:
  - master
  event:
  - push