---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang
  commands:
  - export GO111MODULE=on
  - export GOPROXY=https://goproxy.io
  - go test

---
kind: pipeline
type: docker
name: build

steps:
- name: build
  image: plugins/docker
  registry: registry.shitangdama.cn
  repo: registry.shitangdama.cn/test/laki
  auto_tag: true
    dockerfile: Dockerfile
    username: shitangdama
    password:
      from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

depends_on:
- test

trigger:
  branch:
  - master
  event:
  - push